name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.sqp_4fd579f0fe622e22d6c50f1d0841e8722ca84e14}}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=secure-web-app \
            -Dsonar.sources=.

      - name: Snyk Dependency Scan
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.b9dabc23-f9c3-4643-9d58-e87e19639ddd }}
