name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          SONAR_TOKEN: ${{ secrets.sqp_b2d39e94e10d56f88eac92a47edfec45f4215cc4 }}
          SONAR_HOST_URL: https://secure-web-app.sonarqube

      - name: Snyk Dependency Scan
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.b9dabc23-f9c3-4643-9d58-e87e19639ddd }}
